/**
 * Inventory of tables and fields that must never be exposed via Supabase PostgREST
 * or returned accidentally from Express API responses.
 *
 * Data access: Express → Prisma → PostgreSQL only (no Supabase client SDK).
 */

export const SENSITIVE_FIELD_CATEGORIES = {
  credentials: ['password_hash', 'token'],
  contactPii: ['email', 'phone', 'alternate_phone', 'ip_address', 'user_agent'],
  financial: [
    'balance',
    'current_balance',
    'total_added',
    'total_spent',
    'total_refunds',
    'amount',
    'balance_before',
    'balance_after',
    'subtotal',
    'tax_amount',
    'total_amount',
    'grand_total',
  ],
  vendorPii: ['gst_number', 'full_address', 'pin_code', 'owner_name', 'reference_code', 'employee_code'],
  paymentSecrets: [
    'razorpay_payment_id',
    'razorpay_order_id',
    'razorpay_payment_link_id',
    'razorpay_qr_id',
    'idempotency_key',
    'payload',
  ],
  internalOnly: ['verification_remarks', 'admin_remarks', 'metadata', 'remarks', 'content'],
} as const;

/** Tables flagged as CRITICAL — RLS required, never public */
export const CRITICAL_SENSITIVE_TABLES = [
  'users',
  'refresh_tokens',
  'wallets',
  'wallet_transactions',
  'wallet_balance_snapshots',
  'payments',
  'payment_webhook_logs',
  'financial_audit_logs',
] as const;

/** Tables with PII / vendor / support data */
export const HIGH_SENSITIVE_TABLES = [
  'vendor_profiles',
  'vendor_compliance_requests',
  'vendor_compliance_request_items',
  'vendor_compliance_responses',
  'admin_notes',
  'activity_logs',
  'contact_inquiries',
  'contact_inquiry_notes',
  'contact_inquiry_activities',
  'file_assets',
  'orders',
  'order_items',
  'audit_logs',
] as const;

/** All application tables under RLS lockdown */
export const ALL_APPLICATION_TABLES = [
  'roles',
  'users',
  'vendor_code_sequences',
  'vendor_profiles',
  'delivery_settings',
  'vendor_compliance_requests',
  'vendor_compliance_request_items',
  'vendor_compliance_responses',
  'admin_notes',
  'activity_logs',
  'refresh_tokens',
  'categories',
  'product_families',
  'product_series',
  'product_offerings',
  'product_images',
  'product_offering_versions',
  'configuration_groups',
  'configuration_fields',
  'configuration_options',
  'configuration_rules',
  'quantity_pricing',
  'configuration_option_pricing',
  'pricing_rules',
  'price_snapshots',
  'file_requirements',
  'file_requirement_file_types',
  'file_assets',
  'facilities',
  'departments',
  'workflow_templates',
  'workflow_template_steps',
  'product_offering_workflows',
  'machines',
  'workflow_sla_policies',
  'production_orders',
  'production_order_items',
  'order_item_configurations',
  'order_item_files',
  'workflow_instances',
  'workflow_tasks',
  'workflow_task_history',
  'rework_requests',
  'workflow_sla_breaches',
  'quotes',
  'quote_items',
  'production_job_cards',
  'material_categories',
  'materials',
  'bom_templates',
  'bom_template_items',
  'audit_logs',
  'orders',
  'order_items',
  'wallets',
  'wallet_transactions',
  'payments',
  'payment_webhook_logs',
  'financial_audit_logs',
  'wallet_balance_snapshots',
  'contact_inquiries',
  'contact_inquiry_notes',
  'contact_inquiry_activities',
  'slider_slides',
] as const;
