export const EXECUTION_PERMISSIONS = {
  EXECUTE: 'production.task.execute',
  VIEW_OWN: 'production.task.view.own',
  VIEW_ALL: 'production.task.view.all',
} as const;

export const EXECUTION_TIMELINE_EVENTS = {
  TASK_STARTED: 'TASK_STARTED',
  TASK_PAUSED: 'TASK_PAUSED',
  TASK_RESUMED: 'TASK_RESUMED',
  TASK_HELD: 'TASK_HELD',
  TASK_HOLD_RELEASED: 'TASK_HOLD_RELEASED',
  TASK_COMPLETED: 'TASK_COMPLETED',
  TASK_NOTE_ADDED: 'TASK_NOTE_ADDED',
  TASK_ATTACHMENT_ADDED: 'TASK_ATTACHMENT_ADDED',
  SUPERVISOR_REQUESTED: 'SUPERVISOR_REQUESTED',
  ISSUE_REPORTED: 'ISSUE_REPORTED',
} as const;

export const EXECUTION_ACTIVE_SESSION_STATUSES = [
  'IN_PROGRESS',
  'PAUSED',
  'ON_HOLD',
] as const;

export const EXECUTION_MANAGER_STATUSES = [
  'IN_PROGRESS',
  'PAUSED',
  'ON_HOLD',
  'COMPLETED',
] as const;

export const MAX_PRODUCTION_NOTE_LENGTH = 5000;
export const MAX_ATTACHMENT_LABEL_LENGTH = 200;
