/** Timeline event types. Stable strings — the vendor's tracker renders from these. */
export const SUPPORT_EVENTS = {
  TICKET_RAISED: 'TICKET_RAISED',
  MESSAGE_ADDED: 'MESSAGE_ADDED',
  STAFF_REPLIED: 'STAFF_REPLIED',
  ASSIGNED: 'ASSIGNED',
  STATUS_CHANGED: 'STATUS_CHANGED',
  PRIORITY_CHANGED: 'PRIORITY_CHANGED',
  INFO_REQUESTED: 'INFO_REQUESTED',
  REPRINT_APPROVED: 'REPRINT_APPROVED',
  REPRINT_REJECTED: 'REPRINT_REJECTED',
  REPRINT_ORDER_CREATED: 'REPRINT_ORDER_CREATED',
  ATTACHMENT_ADDED: 'ATTACHMENT_ADDED',
  RESOLVED: 'RESOLVED',
  REOPENED: 'REOPENED',
  CLOSED: 'CLOSED',
  RATED: 'RATED',
} as const;

export type SupportEventType = (typeof SUPPORT_EVENTS)[keyof typeof SUPPORT_EVENTS];

/** In-app notification types. Kept apart from event types: not every event is worth a ping. */
export const SUPPORT_NOTIFICATIONS = {
  TICKET_RAISED: 'SUPPORT_TICKET_RAISED',
  STAFF_REPLIED: 'SUPPORT_STAFF_REPLIED',
  INFO_REQUESTED: 'SUPPORT_INFO_REQUESTED',
  REPRINT_APPROVED: 'SUPPORT_REPRINT_APPROVED',
  REPRINT_REJECTED: 'SUPPORT_REPRINT_REJECTED',
  REPRINT_ORDER_CREATED: 'SUPPORT_REPRINT_ORDER_CREATED',
  RESOLVED: 'SUPPORT_TICKET_RESOLVED',
} as const;

/** Statuses a vendor may still reply on. Beyond these the thread is read-only. */
export const VENDOR_REPLYABLE_STATUSES = [
  'OPEN',
  'UNDER_REVIEW',
  'AWAITING_CUSTOMER',
  'APPROVED',
] as const;
