export const WORKFLOW_DOMAIN_EVENTS = {
  WORKFLOW_CREATED: 'workflow:created',
  WORKFLOW_COMPLETED: 'workflow:completed',
  WORKFLOW_CANCELLED: 'workflow:cancelled',
  TASK_CREATED: 'workflow:task_created',
  TASK_READY: 'workflow:task_ready',
  TASK_COMPLETED: 'workflow:task_completed',
  TASK_ACTIVATED: 'workflow:task_activated',
} as const;

export type WorkflowDomainEvent =
  (typeof WORKFLOW_DOMAIN_EVENTS)[keyof typeof WORKFLOW_DOMAIN_EVENTS];

export const WORKFLOW_TIMELINE_EVENTS = {
  WORKFLOW_CREATED: 'WORKFLOW_CREATED',
  TASKS_GENERATED: 'TASKS_GENERATED',
  TASK_ACTIVATED: 'TASK_ACTIVATED',
  TASK_READY: 'TASK_READY',
  TASK_COMPLETED: 'TASK_COMPLETED',
  WORKFLOW_COMPLETED: 'WORKFLOW_COMPLETED',
  WORKFLOW_CANCELLED: 'WORKFLOW_CANCELLED',
  WORKFLOW_REWORKED: 'WORKFLOW_REWORKED',
  STATUS_CHANGED: 'STATUS_CHANGED',
} as const;

export const DEFAULT_WORKFLOW_TEMPLATE_CODE = 'WF-STANDARD-PRODUCTION';
