export const WORKFLOW_DOMAIN_EVENTS = {
  WORKFLOW_CREATED: 'workflow:created',
  WORKFLOW_COMPLETED: 'workflow:completed',
  WORKFLOW_CANCELLED: 'workflow:cancelled',
  TASK_CREATED: 'workflow:task_created',
  TASK_READY: 'workflow:task_ready',
  TASK_COMPLETED: 'workflow:task_completed',
  TASK_ACTIVATED: 'workflow:task_activated',
} as const;

export type WorkflowDomainEvent =
  (typeof WORKFLOW_DOMAIN_EVENTS)[keyof typeof WORKFLOW_DOMAIN_EVENTS];

export const WORKFLOW_TIMELINE_EVENTS = {
  WORKFLOW_CREATED: 'WORKFLOW_CREATED',
  TASKS_GENERATED: 'TASKS_GENERATED',
  TASK_ACTIVATED: 'TASK_ACTIVATED',
  TASK_READY: 'TASK_READY',
  TASK_COMPLETED: 'TASK_COMPLETED',
  WORKFLOW_COMPLETED: 'WORKFLOW_COMPLETED',
  WORKFLOW_CANCELLED: 'WORKFLOW_CANCELLED',
  WORKFLOW_REWORKED: 'WORKFLOW_REWORKED',
  STATUS_CHANGED: 'STATUS_CHANGED',
  TASK_STARTED: 'TASK_STARTED',
  TASK_PAUSED: 'TASK_PAUSED',
  TASK_RESUMED: 'TASK_RESUMED',
  TASK_HELD: 'TASK_HELD',
  TASK_NOTE_ADDED: 'TASK_NOTE_ADDED',
  TASK_ATTACHMENT_ADDED: 'TASK_ATTACHMENT_ADDED',
  SUPERVISOR_REQUESTED: 'SUPERVISOR_REQUESTED',
  ISSUE_REPORTED: 'ISSUE_REPORTED',
  QC_STARTED: 'QC_STARTED',
  QC_PASSED: 'QC_PASSED',
  QC_FAILED: 'QC_FAILED',
  QC_HELD: 'QC_HELD',
  QC_NOTE_ADDED: 'QC_NOTE_ADDED',
  QC_ATTACHMENT_ADDED: 'QC_ATTACHMENT_ADDED',
  REWORK_REQUESTED: 'REWORK_REQUESTED',
} as const;

export const DEFAULT_WORKFLOW_TEMPLATE_CODE = 'WF-STANDARD-PRODUCTION';
