/**
 * Safe catalog hierarchy migration.
 *
 * Converts auto-generated Family/Series stubs (from the old product-create
 * magic) into explicit managed records without losing ProductOfferings.
 *
 * - Families with slug pattern `{category-slug}-family` are renamed to the
 *   category name when they still use the auto-generated label.
 * - Series that were auto-named after a single product keep their link;
 *   no products are moved or deleted.
 *
 * Usage:
 *   npx dotenv -e .env -e .env.local -- tsx scripts/migrate-catalog-hierarchy.ts
 */
import { PrismaClient } from '@prisma/client';

const prisma = new PrismaClient();

async function main() {
  console.log('Catalog hierarchy migration — preserving all products…');

  const families = await prisma.productFamily.findMany({
    where: { deletedAt: null },
    include: {
      category: { select: { id: true, name: true, slug: true } },
      series: {
        where: { deletedAt: null },
        include: { _count: { select: { offerings: true } } },
      },
    },
  });

  let renamedFamilies = 0;
  let touchedSeries = 0;

  for (const family of families) {
    const autoSlug = `${family.category.slug}-family`;
    const looksAutoGenerated =
      family.slug === autoSlug || family.name === family.category.name;

    if (looksAutoGenerated && family.name === family.category.name) {
      // Keep as managed record under the category; ensure active status.
      await prisma.productFamily.update({
        where: { id: family.id },
        data: {
          isActive: true,
          description:
            family.description ??
            `Managed family for ${family.category.name}. Rename in Admin → Families if needed.`,
        },
      });
      renamedFamilies += 1;
    }

    for (const series of family.series) {
      await prisma.productSeries.update({
        where: { id: series.id },
        data: {
          isActive: true,
          notes:
            series.notes ??
            (series._count.offerings === 1
              ? 'Auto-created series from legacy product create. Rename in Admin → Series if needed.'
              : series.notes),
        },
      });
      touchedSeries += 1;
    }
  }

  const offerings = await prisma.productOffering.count({ where: { deletedAt: null } });
  const orphanOfferings = await prisma.productOffering.count({
    where: {
      deletedAt: null,
      OR: [
        { series: { deletedAt: { not: null } } },
        { series: { family: { deletedAt: { not: null } } } },
      ],
    },
  });

  console.log(`✔ Families reviewed: ${families.length} (annotated: ${renamedFamilies})`);
  console.log(`✔ Series reviewed: ${touchedSeries}`);
  console.log(`✔ Active products: ${offerings}`);
  if (orphanOfferings > 0) {
    console.warn(`⚠ Products linked to deleted family/series: ${orphanOfferings}`);
  } else {
    console.log('✔ No orphan products');
  }
  console.log('Migration complete. Manage catalog via Admin → Categories / Families / Series / Products.');
}

main()
  .catch((error) => {
    console.error('Migration failed', error);
    process.exitCode = 1;
  })
  .finally(async () => {
    await prisma.$disconnect();
  });
